spring:
  data:
    mongodb:
      host: mongodb
      database: store
      authentication-database: store
      uri: ${MONGODB_URI}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
        provider:
          google:
            issuerUri: https://accounts.google.com

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG
